In [5]:
import numpy as np

In [6]:
list=[1,12.5,23]
np.array(list)

array([ 1. , 12.5, 23. ])

In [7]:
arr=np.array([1,12.5,23])
arr

array([ 1. , 12.5, 23. ])

In [ ]:
np.arrange(1,12.5,23)


In [3]:
listoflist=([1,2,4],[45,63,25],[22,33,1])
np.array(listoflist)

NameError: name 'np' is not defined

In [4]:
np.arange(5,28)

NameError: name 'np' is not defined

In [ ]:
np.zeros(5)

In [ ]:
np.zeros(5,dtype=int)

In [ ]:
np.ones(5)

In [ ]:
np.linspace(0,20,10)

In [ ]:
np.eye(5)

In [ ]:
np.eye(5,dtype=int)

In [ ]:
np.random.rand(2,4)

In [ ]:
np.random.randn(2,4)

In [ ]:
np.random.randint(2,4)

In [ ]:
np.random.randint(5,6)

In [ ]:
np.random.randint(5,8)

In [ ]:
np.random.randint(0,10,15)

In [ ]:
list

In [ ]:
new=np.random.randint(0,10,15)
new

In [ ]:
new.min()

In [ ]:
new.argmin()

In [ ]:
new.argmax()

In [ ]:
new.T

In [ ]:
np.array(new)

In [ ]:
new.dtype

In [ ]:
a=np.eye(5)
a

In [ ]:
listoflist=([1,2,4],[45,63,25],[22,33,1])
np.array(listoflist)

In [ ]:
x=np.array(listoflist)

In [ ]:
x

In [ ]:
x.T

In [ ]:
y=np.random.rand(4,3)

In [ ]:
np.random.rand(4,3).T

In [ ]:
x.reshape(3,4)

In [ ]:
y=np.random.rand(4,3)

In [ ]:
y

In [ ]:
y.reshape(3,4)

In [9]:
listoflist=([1,2,4],[45,63,25],[22,33,1])
z=np.array(listoflist)

In [10]:
z

array([[ 1,  2,  4],
       [45, 63, 25],
       [22, 33,  1]])

In [11]:
z[2][2]

1

In [ ]:
z[1][2]

In [ ]:
z

In [ ]:
z[:][1]

In [ ]:
z

In [ ]:
z[:,1]

In [ ]:
z[]

In [ ]:
z[1:3][2:4]

In [ ]:
z[1:,2:]

In [ ]:
z[1:1][2:3]

In [ ]:
z[1:1][2:2]

In [ ]:
np.sqrt(z)

In [ ]:
np.log(z)

In [ ]:
np.exp(z)

In [ ]:
z

In [ ]:
z

In [1]:
z

NameError: name 'z' is not defined

In [8]:
z

NameError: name 'z' is not defined

In [12]:
z

array([[ 1,  2,  4],
       [45, 63, 25],
       [22, 33,  1]])

In [13]:
z[:][1]

array([45, 63, 25])

In [14]:
z[:,1]

array([ 2, 63, 33])

In [15]:
z[1,:]

array([45, 63, 25])

In [16]:
z[:][1][2]

25